repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", #only display messages
            "-sn", #do not display the score
            "--rcfile=.pylintrc", #link to config file
            "--load-plugins=pylint.extensions.docparams" #load an extension
          ] 